### ISSUE TITLE
Empty line stops gcode parsing

### ISSUE THREAD

**Issue by foobarjimmy** [kadirilkimen/polarToolsJS#1]
**The problem**
First empty line in the gcode file stops gcode parsing.

**What is version of polarToolsJS has the issue?**
Latest

**What type of web server are you running?**
full apache2 web server with php enabled on docker

**How to solve the problem?**
Parsing the same file after empty lines are removed before uploading to index.php fixed the issue.

**Comment by kadirilkimen** [comment]
It's fixed.
Thanks for your contribution.
